import { Experience, Project, Skill, SocialLink } from "@/types";

export const experiences: Experience[] = [
  {
    id: "dias",
    company: "Dias (Atlastek)",
    position: "Software Engineer",
    period: "March 2025 - Present",
    location: "Turkey",
    description:
      "Working on enterprise-level B2G applications focusing on tracking and management systems.",
    achievements: [
      "Developed and maintained other enterprise-level applications using .NET 9 and microservices architecture",
      "Maintained UTTS (Ulusal Taşıt Tanıma Sistemi) system for fuel and vehicle management with advanced monitoring capabilities",
      "Implemented comprehensive tracking solutions with real-time data processing",
      "Worked with PostgreSQL, Redis, RabbitMQ for scalable backend systems",
      "Utilized Docker and Kubernetes for containerized deployments",
    ],
    technologies: [
      ".NET 9",
      "C#",
      "Entity Framework Core",
      "PostgreSQL",
      "Redis",
      "RabbitMQ",
      "Docker",
      "Kubernetes",
      "Microservices",
      "RESTful APIs",
    ],
    type: "current",
  },
  {
    id: "wiro-ai",
    company: "Wiro AI",
    position: "Software Engineer",
    period: "July 2023 – February 2025",
    location: "Istanbul, Turkey",
    description:
      "Lead development on multiple projects enhancing task management and system monitoring in AI/ML infrastructure. Specialized in creating web applications and maintaining robust APIs with multiple access levels.",
    achievements: [
      "Led development on multiple AI/ML projects with complex task management and system monitoring",
      "Built Blazor fullstack web application with Tailwind CSS for ML engineers to test configured models",
      "Developed AIWorker project running on Linux machines with NVIDIA GPU support using Docker",
      "Created AIController project for distributing LLM requests between web project and end-user websites",
      "Maintained robust REST API project with internal and external API endpoints using clean architecture",
      "Implemented real-time features using SignalR for live system monitoring and updates",
      "Managed project rollouts and utilized GitHub for version control in fast-paced environment",
    ],
    technologies: [
      ".NET 8",
      "Blazor",
      "C#",
      "PostgreSQL",
      "Redis",
      "Entity Framework",
      "Docker",
      "Linux",
      "NVIDIA GPU",
      "REST APIs",
      "Clean Architecture",
      "Tailwind CSS",
      "SignalR",
      "GitHub",
    ],
    type: "previous",
  },
  {
    id: "jetlink",
    company: "Jetlink",
    position: "Full Stack Engineer",
    period: "January 2021 - July 2023",
    location: "Istanbul, Turkey",
    description:
      "Worked at a chatbot company with multi-project architecture enabling businesses to deploy intelligent chatbots. Led legacy system modernization and managed both cloud and on-premises deployments.",
    achievements: [
      "Developed and maintained multi-project chatbot platform: CMS (MVC), REST APIs, end-user UI, and reporting system",
      "Led technology migration from .NET 4.7 to .NET 6 with improved architecture design",
      "Built comprehensive REST API project for internal and external integrations",
      "Created end-user chatbot UI components for deployment on company websites",
      "Developed scheduled reporting system for analytics and performance monitoring",
      "Managed deployments on Windows Server with IIS for both cloud and on-premises clients",
      "Implemented webhook integrations triggering CRM requests and social media API integrations",
      "Modernized legacy codebase while maintaining system stability and performance",
    ],
    technologies: [
      ".NET 4.7",
      ".NET 6",
      "ASP.NET MVC",
      "MongoDB",
      "WebSockets",
      "JavaScript",
      "TypeScript",
      "React",
      "RESTful APIs",
      "Windows Server",
      "IIS",
      "Webhook Integration",
      "Social Media APIs",
    ],
    type: "previous",
  },
];

export const projects: Project[] = [
  {
    id: "Dias",
    name: "Enterprise Management Platform",
    type: "B2G",
    description:
      "Comprehensive enterprise management system with real-time monitoring, tracking capabilities, and advanced analytics for large-scale operations.",
    technologies: [
      ".NET 9",
      "MassTransit",
      "PostgreSQL",
      "Kubernetes",
      "Helm",
      "Microservices",
      "Event Driven Architecture with clean architecture",
      "Message Queuing",
      "GitLab",
    ],
    features: [
      "Real-time asset tracking and monitoring",
      "Resource consumption analysis and optimization",
      "Advanced diagnostics and performance monitoring",
      "Behavioral analysis and reporting system",
      "Automated maintenance and scheduling system",
    ],
    role: "Software Engineer",
    company: "Dias (Atlastek)",
    status: "active",
  },
  {
    id: "Atlastek",
    name: "Enterprise Asset Tracking System",
    type: "B2G",
    description:
      "Enterprise-level tracking and monitoring system with comprehensive reporting and compliance features for regulated industries.",
    technologies: [
      ".NET 9",
      "Entity Framework Core",
      "PostgreSQL",
      "Redis",
      "Docker",
      "RESTful APIs",
      "Clean Architecture",
      "Microservices",
      "GitLab",
    ],
    features: [
      "Real-time production and distribution tracking",
      "Compliance reporting and auditing system",
      "Multi-tenant architecture with role-based access",
      "Advanced analytics dashboard with real-time metrics",
      "Automated regulatory reporting and submissions",
      "Scalable microservices architecture",
    ],
    role: "Software Engineer",
    company: "Dias (Atlastek)",
    status: "completed",
  },
  {
    id: "wiro-ai-platform",
    name: "Wiro AI - ML Infrastructure Platform",
    type: "B2B",
    description:
      "Comprehensive AI/ML platform consisting of multiple interconnected projects for model testing, request distribution, and GPU-based processing with real-time monitoring.",
    technologies: [
      ".NET 8",
      "Blazor",
      "PostgreSQL",
      "Redis",
      "Entity Framework",
      "Docker",
      "Linux",
      "NVIDIA GPU",
      "REST APIs",
      "Clean Architecture",
      "Tailwind CSS",
      "SignalR",
      "GitHub",
    ],
    features: [
      "Worker: GPU-based processing on Linux machines with NVIDIA support",
      "Controller: Intelligent LLM request distribution system",
      "Blazor Web App: ML engineer interface for model testing and configuration",
      "REST API: Internal and external API endpoints with multiple access levels",
      "Real-time monitoring with SignalR for system performance tracking",
      "Docker containerization for scalable deployment across Linux infrastructure",
    ],
    role: "Software Engineer",
    company: "Wiro AI",
    status: "completed",
  },
  {
    id: "jetlink-platform",
    name: "Jetlink - Multi-Project Chatbot Platform",
    type: "B2B",
    description:
      "Comprehensive chatbot platform consisting of multiple interconnected projects including CMS, APIs, end-user interfaces, and reporting systems. Successfully migrated from legacy .NET 4.7 to modern .NET 6 architecture.",
    technologies: [
      ".NET 4.7",
      ".NET 6",
      "ASP.NET MVC",
      "MongoDB",
      "WebSockets",
      "React",
      "TypeScript",
      "JavaScript",
      "RESTful APIs",
      "Windows Server",
      "IIS",
      "Webhook Integration",
      "Social Media APIs",
      "Bitbucket",
    ],
    features: [
      "CMS Project: MVC-based chatbot management system with hybrid React components",
      "API Project: Internal and external REST APIs for system integrations",
      "End-User UI: Chatbot interface components for deployment on client websites",
      "Reporting System: Scheduled analytics and performance monitoring system",
      "Legacy Migration: Successfully modernized from .NET 4.7 to .NET 6",
      "Multi-deployment: Cloud and on-premises deployment management with IIS",
      "Real-time Communication: WebSocket implementation for live chatbot interactions",
      "Social Integrations: WhatsApp, Facebook, Instagram API integrations",
    ],
    role: "Full Stack Developer",
    company: "Jetlink",
    status: "completed",
  },
];

export const skills: Skill[] = [
  // Backend
  { name: ".NET Core/9", category: "backend", proficiency: "expert" },
  { name: "C#", category: "backend", proficiency: "expert" },
  { name: "Entity Framework Core", category: "backend", proficiency: "expert" },
  { name: "ASP.NET Core", category: "backend", proficiency: "expert" },
  { name: "Node.js", category: "backend", proficiency: "proficient" },
  { name: "RESTful APIs", category: "backend", proficiency: "expert" },
  { name: "Microservices", category: "backend", proficiency: "proficient" },
  { name: "RabbitMQ", category: "backend", proficiency: "proficient" },

  // Frontend
  { name: "TypeScript", category: "frontend", proficiency: "proficient" },
  { name: "JavaScript", category: "frontend", proficiency: "proficient" },
  { name: "React", category: "frontend", proficiency: "intermediate" },
  { name: "Angular", category: "frontend", proficiency: "intermediate" },
  { name: "Blazor", category: "frontend", proficiency: "proficient" },
  { name: "HTML/CSS", category: "frontend", proficiency: "proficient" },
  { name: "Tailwind CSS", category: "frontend", proficiency: "proficient" },

  // Database
  { name: "PostgreSQL", category: "database", proficiency: "proficient" },
  { name: "Redis", category: "database", proficiency: "proficient" },
  { name: "SQL Server", category: "database", proficiency: "proficient" },
  { name: "MongoDB", category: "database", proficiency: "intermediate" },

  // Tools & DevOps
  { name: "Docker", category: "tools", proficiency: "proficient" },
  { name: "Git", category: "tools", proficiency: "proficient" },
  { name: "Linux", category: "tools", proficiency: "proficient" },
];

export const socialLinks: SocialLink[] = [
  {
    name: "GitHub",
    url: process.env.NEXT_PUBLIC_GITHUB_URL || "",
    icon: "Github",
  },
  {
    name: "LinkedIn",
    url: process.env.NEXT_PUBLIC_LINKEDIN_URL || "",
    icon: "Linkedin",
  },
  {
    name: "Email",
    url: `mailto:${process.env.NEXT_PUBLIC_CONTACT_EMAIL || ""}`,
    icon: "Mail",
  },
];
